//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventAideEntities : DbContext
    {
        public EventAideEntities()
            : base("name=EventAideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_bday> tbl_bday { get; set; }
        public virtual DbSet<tbl_bookings> tbl_bookings { get; set; }
        public virtual DbSet<tbl_bookmarks> tbl_bookmarks { get; set; }
        public virtual DbSet<tbl_budgeter> tbl_budgeter { get; set; }
        public virtual DbSet<tbl_checklist> tbl_checklist { get; set; }
        public virtual DbSet<tbl_cities> tbl_cities { get; set; }
        public virtual DbSet<tbl_company> tbl_company { get; set; }
        public virtual DbSet<tbl_dispImg> tbl_dispImg { get; set; }
        public virtual DbSet<tbl_gallery> tbl_gallery { get; set; }
        public virtual DbSet<tbl_messages> tbl_messages { get; set; }
        public virtual DbSet<tbl_notification> tbl_notification { get; set; }
        public virtual DbSet<tbl_otherParty> tbl_otherParty { get; set; }
        public virtual DbSet<tbl_provinces> tbl_provinces { get; set; }
        public virtual DbSet<tbl_rating> tbl_rating { get; set; }
        public virtual DbSet<tbl_reunion> tbl_reunion { get; set; }
        public virtual DbSet<tbl_services> tbl_services { get; set; }
        public virtual DbSet<tbl_Task> tbl_Task { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_wedding> tbl_wedding { get; set; }
    }
}
