//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_notification
    {
        public int notifID { get; set; }
        public string notifContent { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> notifDate { get; set; }
        public Nullable<int> seen { get; set; }
        public string type { get; set; }
    }
}
