//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bday
    {
        public int BirthdayID { get; set; }
        public string EventName { get; set; }
        public string CelebFirstN { get; set; }
        public string CelebLastN { get; set; }
        public Nullable<int> CurAge { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> ProvID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> EstimatedBudget { get; set; }
        public Nullable<int> userID { get; set; }
    }
}
