//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_wedding
    {
        public int WeddingID { get; set; }
        public string EventName { get; set; }
        public string GroomFirstN { get; set; }
        public string GroomLastN { get; set; }
        public string BrideFirstN { get; set; }
        public string BrideLastN { get; set; }
        public System.DateTime EventDate { get; set; }
        public int ProvinceID { get; set; }
        public int CityID { get; set; }
        public int EstimatedBudget { get; set; }
        public int userID { get; set; }
    }
}
