//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;

    public partial class tbl_checklist
    {
        public int ChecklistID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> IsFinished { get; set; }
        public Nullable<int> userID { get; set; }
        public string eventType { get; set; }
        public Nullable<int> eventID { get; set; }
        public string notes { get; set; }
        public List<string> TaskName { get; set; }
        public List<string> ServiceID { get; set; }
    }
}
