//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_budgeter
    {
        public int ID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> BookCompany { get; set; }
        public Nullable<int> CostEstimate { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<int> eventID { get; set; }
        public string eventType { get; set; }
        public Nullable<int> userID { get; set; }
    }
}
