//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bookings
    {
        public int BookID { get; set; }
        public string eventTitle { get; set; }
        public string BookMsg { get; set; }
        public string BookDate { get; set; }
        public string BookDateEnd { get; set; }
        public Nullable<int> eventID { get; set; }
        public string eventType { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> BookStatus { get; set; }
        public string BookSched { get; set; }
        public string CancelDate { get; set; }
        public string Terms { get; set; }
    }
}
